title: My Not-So-Awesome Site
author: Joshua Whiting and some Github Learning Bot that keeps telling him what to do
email: bob@bob.com
description: > # this means to ignore newlines until "baseurl:"
  This is neat.

# social links
twitter_username: jdwhiting
github_username:  jdwhiting

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
